### ISSUE TITLE
Can StaSy be used for tabular data augmentation?

### ISSUE THREAD

**Issue by zhxfei** [JayoungKim408/STaSy#2]
Hi! 

I would like to ask if this project can be used for data augmentation? for example, I have few tabular data and I would like to know if StaSy works well with a small amount data?

Actually i am tring to do this on UCI credit card dataset, i have constructed 50 samples which sampled from original dataset, but it seems that it doesn't work very well.

Could you give me some advice on this?  Thanks!

**Comment by JayoungKim408** [comment]
Hi! 

First of all, please make sure if the model has trained appropriately. The default setting of the code may construct too big model for your small dataset. You can control the model architecture by modifying hidden_dims. 
And if you've changed training epoch to a smaller value, the training may not be done appropriately, because due to the self paced learning, all of the training samples are involved to training after 10,000 epochs.

**Comment by zhxfei** [comment]
Thanks for your kind advice, modifying the hidden_dims helps me a lot. I will close this issue.
